author: Wyvernix
database: false
description: A plugin for The Civilizations Server.
main: me.Wyvernix.CivServerCore.CivCore
name: Civilizations Server Core
startup: postworld
version: '1.0'
commands:
  civserver:
    description: Tests plugin.
    usage: /<command>
    aliases: [cs, civserv]